// Re-exported so frontend can switch on stable error codes
// Source of truth lives in apps/api/src/common/errors.ts

export const ERR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_003',
  AUTH_INSUFFICIENT_PERMISSION: 'AUTH_004',
  AUTH_USER_INACTIVE: 'AUTH_005',
  RATE_LIMIT_EXCEEDED: 'RATE_001',
  JOB_CARD_NOT_FOUND: 'JC_001',
  JOB_CARD_INVALID_TRANSITION: 'JC_002',
  JOB_CARD_BALANCE_NOT_ZERO: 'JC_003',
  JOB_CARD_VERSION_CONFLICT: 'JC_004',
  WORK_ORDER_NOT_FOUND: 'WO_001',
  WORK_ORDER_NO_WORKER: 'WO_002',
  WORK_ORDER_WORKER_BRANCH: 'WO_003',
  WORK_ORDER_INVALID_SPEC: 'WO_004',
  WORK_ORDER_INVALID_TRANSITION: 'WO_005',
  PAYMENT_OFFLINE_BLOCKED: 'PAY_001',
  PAYMENT_ADVANCE_TOO_LOW: 'PAY_002',
  STOCK_INSUFFICIENT: 'INV_001',
  PRICE_NOT_FOUND: 'PL_001',
  CUSTOMER_PHONE_EXISTS: 'CUS_001',
  CUSTOMER_NOT_FOUND: 'CUS_002',
  WORKER_NOT_FOUND: 'WRK_001',
  WORKER_INACTIVE: 'WRK_002',
  SYNC_EVENT_TOO_OLD: 'SYNC_001',
  SYNC_PAYMENT_BLOCKED: 'SYNC_002',
} as const;

export type ErrCode = (typeof ERR_CODES)[keyof typeof ERR_CODES];
